# Generated by Django 5.2.9 on 2025-12-07 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0002_letter_is_archived_letter_is_read_letter_is_starred_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='letter',
            old_name='is_archived',
            new_name='is_deleted_recipient',
        ),
        migrations.RenameField(
            model_name='letter',
            old_name='is_deleted',
            new_name='is_deleted_sender',
        ),
        migrations.RenameField(
            model_name='letter',
            old_name='is_read',
            new_name='is_draft',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='is_starred',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='read_at',
        ),
        migrations.AlterField(
            model_name='letter',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_letters', to=settings.AUTH_USER_MODEL),
        ),
    ]
