# Generated by Django 5.2.9 on 2025-12-28 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0004_letter_sent_at_alter_letter_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='letters.letter'),
        ),
        migrations.AddField(
            model_name='letterattachment',
            name='original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
