# Generated by Django 5.2.9 on 2025-12-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0005_letter_parent_letterattachment_original_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterattachment',
            name='file',
            field=models.FileField(upload_to='uploads/letter_attachments/'),
        ),
    ]
