# Generated by Django 5.2.9 on 2025-12-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskattachment',
            name='original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
