# Generated by Django 5.2.9 on 2025-12-31 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskattachment_original_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksubmission',
            old_name='description',
            new_name='comment',
        ),
    ]
