# Generated by Django 5.2.9 on 2025-12-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_description_tasksubmission_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
